### user auth token
POST http://localhost:8080/v1/users/auth/hack
Content-Type: application/json

### create roles
POST http://localhost:8080/v1/roles
Content-Type: application/json
Authorization: Bear eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKV1MgLSBIQUNLIiwicmVhbG0iOnsicmVhbG1zIjpbInN1cGVyIl0sInVzZXJOYW1lIjoiSEFDSyIsInVzZXJJZCI6Ii0yMzM2NDE0OTQ1MDgwMzgxMzAzIn0sImV4cCI6MTYxNjk3MTE0NTc1NiwiaWF0IjoxNjE2OTQyMzQ1NzU2LCJqdGkiOiI5ZWE5ZmY3My00NWUwLTQ4MWYtOTA2Ny04ZTFiNDdkODkzZDUifQ.jICL2PBu-izbxVLzR-0StGLBevs1ovVjnMjzUggyVO0

{
  "name": "THAT_ROLE",
  "description": "Role for testing"
}

### get role list
GET http://localhost:8080/v1/roles

### create realm
POST http://localhost:8080/v1/roles/realms
Content-Type: application/json
Authorization: Bear eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKV1MgLSBIQUNLIiwicmVhbG0iOnsicmVhbG1zIjpbInN1cGVyIl0sInVzZXJOYW1lIjoiSEFDSyIsInVzZXJJZCI6Ii0yMzM2NDE0OTQ1MDgwMzgxMzAzIn0sImV4cCI6MTYxNjk3MTE0NTc1NiwiaWF0IjoxNjE2OTQyMzQ1NzU2LCJqdGkiOiI5ZWE5ZmY3My00NWUwLTQ4MWYtOTA2Ny04ZTFiNDdkODkzZDUifQ.jICL2PBu-izbxVLzR-0StGLBevs1ovVjnMjzUggyVO0

{
  "name": "G_REALM",
  "description": "Realm for testing"
}

### get realm list
GET http://localhost:8080/v1/roles/realms

### get realm list for specified role
GET http://localhost:8080/v1/roles/b06/realms

### create role realm setting
POST http://localhost:8080/v1/roles/realm-settings
Content-Type: application/json
Authorization: Bear eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKV1MgLSBIQUNLIiwicmVhbG0iOnsicmVhbG1zIjpbInN1cGVyIl0sInVzZXJOYW1lIjoiSEFDSyIsInVzZXJJZCI6Ii0yMzM2NDE0OTQ1MDgwMzgxMzAzIn0sImV4cCI6MTYxNjk3MTE0NTc1NiwiaWF0IjoxNjE2OTQyMzQ1NzU2LCJqdGkiOiI5ZWE5ZmY3My00NWUwLTQ4MWYtOTA2Ny04ZTFiNDdkODkzZDUifQ.jICL2PBu-izbxVLzR-0StGLBevs1ovVjnMjzUggyVO0

{
  "role_realms": [
    {
      "role_id": "b06f57e9-acc6-40cc-a881-a6f8f8f71e00",
      "realm_ids": ["1545ee91-9c81-4650-a2f1-09be16f4796e", "1cd030ae-b8a1-4578-93cf-e9e8e8d44f4f"]
    },
    {
      "role_id": "98d69db0-4742-4bf8-96b7-7f50c3e23fd7",
      "realm_ids": ["1545ee91-9c81-4650-a2f1-09be16f4796e", "1cd030ae-b8a1-4578-93cf-e9e8e8d44f4f"]
    }
  ]
}
