### user auth token
POST http://localhost:8080/v1/users/auth/hack
Content-Type: application/json

### create user
POST http://localhost:8080/v1/roles
Content-Type: application/json
Authorization: Bear eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKV1MgLSBIQUNLIiwicmVhbG0iOnsicmVhbG1zIjpbInN1cGVyIl0sInVzZXJOYW1lIjoiSEFDSyIsInVzZXJJZCI6IjIwNDE3MzkxNzY1OTA4MTIzNzcifSwiZXhwIjoxNjE2ODc5NDAyODkzLCJpYXQiOjE2MTY4NTA2MDI4OTMsImp0aSI6IjY5ZWJlZjIwLWNhMzAtNDI1ZS04NWRiLTNhODc1NGI5YjQ3ZCJ9.qsFdkmT1cbT11ZhpFf8Fca2QTgFQl3fU_uGxWZAu5mc

{
  "name": "ADMIN",
  "description": "The system administrator"
}

### get role list
GET http://localhost:8080/v1/roles


### get role list
GET http://localhost:8080/v1/roles/realms

