### user auth token
GET {{base_url}}/v1/token

> {% client.global.set("api_token", response.body); %}


### submit with token
POST {{base_url}}/v1/tests/api-idempotence
Idempotent-Api-Token: {{api_token}}


### test api limit
POST {{base_url}}/v1/tests/api-limit


### test api user limit
POST {{base_url}}/v1/tests/api-user-limit