### user auth token
POST http://localhost:8080/v1/auth/hacker
Content-Type: application/json

> {% client.global.set("auth_token", response.body); %}

### create user
POST http://localhost:8080/v1/users
Content-Type: application/json
Authorization: Bear {{auth_token}}}}

{
  "name": "foobar",
  "password": "q1w2e3r4!!"
}

### get user info
GET http://localhost:8080/v1/users/1