### user auth token
POST http://localhost:8080/v1/users/auth/hack
Content-Type: application/json


### create user
POST http://localhost:8080/v1/users
Content-Type: application/json
Authorization: Bear eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKV1MgLSBIQUNLIiwicmVhbG0iOnsicmVhbG1zIjpbInN1cGVyIl0sInVzZXJOYW1lIjoiSEFDSyIsInVzZXJJZCI6Ii0yMDAyMjcyODQxNzcxOTA1Nzk3In0sImV4cCI6MTYxNzAxOTk2MjA3NSwiaWF0IjoxNjE2OTkxMTYyMDc1LCJqdGkiOiJjNjE0ZTBlNS0zZDdjLTQwY2QtYWFjOS0xNTZkYzVjZmY4OTcifQ.RbBJktu1MqJ4BKwOGyXmPhDvOU0SIJsRWAFAjYgybIc

{
  "name": "hacker",
  "mobile_phone": "13800000590",
  "password": "Asdf1234!!!!"
}

### get user info
GET http://localhost:8080/v1/users/3

