apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: backoffice
images:
- name: backoffice-image
  newName: xmniko/backoffice
  newTag: bb995b82f15f45913f2041431f30bd1c5e629816
