spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://mysql-svc.mysql:3306/main
    username: root
    password: root
  redis:
    host: redis-svc.redis
    port: 6379
    ssl: false
    database: 0
    timeout: 1000
    password: Hello1234!!!!
  task:
    execution:
      pool:
        core-size: 4
        max-size: 4

management:
  endpoints:
    web:
      exposure:
        include: "info, health, beans, caches, env, httptrace, mappings, heapdump, threaddump, prometheus"
    health:
      show-details: ALWAYS
