spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/main
    username: dev
    password: dev
  redis:
    url: redis://localhost:6379
    ssl: false
    database: 0
    timeout: 1000
    password:
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20
  task:
    execution:
      pool:
        core-size: 4
        max-size: 4

management:
  endpoints:
    web:
      exposure:
        include: "info, health, beans, caches, env, httptrace, mappings, heapdump, threaddump, prometheus"
    health:
      show-details: ALWAYS
