spring:
  profiles:
    active: dev

server:
  compression:
    enabled: true
    mime-types: text/xml, application/json, application/xml
    min-response-size: 2048
  undertow:
    accesslog:
      pattern: "%h %l %u %t \"%r\" %s %b \"%{i,Referer}\" \"%{i,User-Agent}\" %D"

sfe4j:
  title: "SFE4J Demo"
  description: "Simple File Explorer for spring-boot based Java Web Application."
  quick-links:
    root: "/"
    logs: "/data/logs"
  base-dir-path: "/"
  restrict-to-base-dir: false
