spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/main
    username: dev
    password: dev
  redis:
    url: redis://localhost:6379

management:
  endpoints:
    web:
      exposure:
        include: "info, health, beans, caches, env, httptrace, mappings, heapdump, threaddump, prometheus"
    health:
      show-details: ALWAYS
